### ISSUE TITLE
Uncaught ReferenceError: getAppRestrictions is not defined

### ISSUE THREAD

**Issue by ndubbaka** [isw-kudos/cordova-plugin-android-mdm#2]
I get the following error after cordova run android
```"Uncaught ReferenceError: getAppRestrictions is not defined", source: file:///android_asset/www/js/application.js (64)```

1. I added the plugin using cordova plugin add cordova-plugin-android-mdm --save
2. Created app_restrictions.xml
3. Added strings to platforms/android/res/values/strings.xml

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">myappname</string>
    <string name="launcher_name">@string/app_name</string>
    <string name="activity_name">@string/launcher_name</string>
    <string name="title_message">title_message</string>
    <string name="description_message">description_message</string>
    <string name="default_message">default_message</string>
</resources>
```

**Comment by markdon** [comment]
Hey sorry I only just noticed your issue,

Try androidmdm.getAppRestrictions() or window.androidmdm.getAppRestrictions()
